# Generated by Django 4.2.4 on 2023-08-30 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('fabidecor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temas',
            name='imagens',
            field=models.ManyToManyField(related_name='+', to='uploader.image'),
        ),
        migrations.AlterField(
            model_name='temas',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fabidecor', to='fabidecor.categoria'),
        ),
    ]
