# Generated by Django 4.2.4 on 2023-08-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabidecor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalago',
            options={'verbose_name': 'Catálogo'},
        ),
    ]
