# Generated by Django 4.2.4 on 2023-09-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabidecor', '0003_categoria_imagens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicionais', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='isbn',
        ),
    ]
