# Generated by Django 4.2.4 on 2023-09-06 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('fabidecor', '0005_remove_temas_isbn_produto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagens',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
    ]
