# Generated by Django 4.2.4 on 2023-09-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabidecor', '0006_produto_imagens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.URLField(blank=True, null=True)),
                ('endereco', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'cliente',
            },
        ),
        migrations.DeleteModel(
            name='Informacoes',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='temas',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='temas',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='temas',
            name='titulo',
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='temas',
            name='descricao',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
