# Generated by Django 4.2.4 on 2023-09-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabidecor', '0007_clientes_delete_informacoes_remove_categoria_tema_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
